### PR TITLE
Add: java args to dockerfile and update readme

### PR DESCRIPTION
**Pull request by sachincool**

### CODE REVIEW

**Comment by sachincool** [comment]
fix https://github.com/blacktop/docker-cuckoo/issues/28

**Comment by mayurah** [comment]
For me, adding below for **elasticsearch** worked.

>
     environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g

**Comment by sachincool** [comment]
Great addition! I wish I could update it now, but I already deleted the fork. Also @mayurah check your FB messenger once :P I left a message back in 2017.. Weird coincidence. Great to see you here

**Comment by blacktop** [comment]
added, thank you 👍

**Pull request closed without merging**
