### PR TITLE
Add new features

### PR DESCRIPTION
**Pull request by wroersma**
Add 
- [x] tcpdump
- [x] clamav
- [x] malheur
- [x] suricata
- [x] yara

I have a few other things working as well but it would likely require far to many changes on your end as I'm using a cuckoo fork. I do have KVM working with this all etc with memory dumps etc. I have a little problem with mitmdump not starting the proxy properly but that should be working in no time.

### CODE REVIEW

**Comment by blacktop** [comment]
Yara was already installed because the base image was volatility which was built on yara?

**Comment by wroersma** [comment]
It installs yara from source instead.

**Comment by blacktop** [comment]
So does the volatility image https://github.com/blacktop/docker-yara/blob/master/3.7/Dockerfile

**Comment by blacktop** [comment]
I appreciate this pull request and your time, but am unsure about some of the choices you have made that don't seem very "docker-ish", meaning, not following best practices and trying to attain the smallest possible docker image.  Do you want to learn them and fix the pull request or I can try to fix them after/before I merge?

**Comment by wroersma** [comment]
I would be happy to come back and optimize this when I finish the project I'm working on then I can come back to this. I should take more time to convert it to how you had it so I will do that. I'm pretty far removed from this where I'm at. I should be able to get it within the next week.

**Comment by wroersma** [comment]
One question though do you want all services like suricata pulled from a dedicated repo for each?

**Comment by blacktop** [comment]
I don't think so, it worked out nicely before because I made the Yara image, and then I made the volatility one and it needed Yara so I was able to save time/work by using Yara as the base for Voliatility and THEN when I started cuckoo and saw it needed Yara and volatility I could safe 2 deps by using that base image and NOW in docker i can set it up so that in DockerHUB it knows that cuckoo depends on those other images so if I perform a bug fix in one of them it will automatically rebuild the cuckoo image to pull in those fixes making the whole thing easier to maintain.

I am not sure if the other deps depend on volatility and yara or a combination of the others that would allow for the same time saving automation do you?

**Comment by blacktop** [comment]
Another thing you want to keep in mind is docker images are not VMs and one of the goals is to keep them as small as possible, this serves two purposes.

1) These images will be sent over the network so keeping them small keeps download times short.
2) Keeping them small means not having stuff that you don't need to run the application, which in turn decreases the attack surface making it much harder for someone to hack the docker container

So for example you don't want to have `pip` or `python-dev` left in an image because it adds a lot of size to the overall image.

You can run `make size` in the repo to see how your changes have affected the overall size of the image as it will also update the sizes in the README.

**Comment by wroersma** [comment]
I mean again these are just quick things I attempted to bring over from where I'm at. tcpdump, suricata, mitmdump are their own containers processing and handling data from a MQ server. To be really best practices the cuckoo daemon system shouldn't have host access or tcpdump etc. That should be a dedicated container that needs to properly dump and control the network and also support the cuckoo rooter service. None of the storage should be in local docker volumes in my opinion as well that should all be served out to like swift or s3 and have no report files stored locally.

**Comment by blacktop** [comment]
I agree but this also needs to be the most general solution meaning works for most people and most people who would be interested in the docker solution would want to have it up and running quickly to just play around with it and to try out cuckoo locally.

So it would be cool to have a normal version and then a AWS solution and an Openstack solution etc etc

**Comment by blacktop** [comment]
It would be bad ass to have a version that can be deployed to Kubernetes too 👍 😎 👍

**Comment by wroersma** [comment]
That's something we are looking at :) I'm also changing cuckoo a good amount though. Python3 and a long list of other things I'm not a fan of.

**Comment by blacktop** [comment]
Yeah I don't like the idea of changing cuckoo because now it "owns" you. Then if you ever want to fold in their new features later on you gotta push that boulder back up the hill. 😞

**Comment by blacktop** [comment]
However, if you are going to maintain that boulder it can be a **blacktop/cuckoo:`<tag>`** 😉

**Comment by wroersma** [comment]
We do intend to maintain it :) Though we don't have much plans for adding any of their future stuff in. I mean we will start to gut it and I think I don't even think I can use the community sigs at this point unless I fork them as well and change them. I'm not sure where it will end up.

**Comment by wroersma** [comment]
If you have time feel free to take out what you need and put it in. I will just close this out and recreate the entire thing and make a clean pull request from a well tested state.

**Comment by blacktop** [comment]
👍

**Pull request closed without merging**
